apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  restartPolicy: Always
  containers:
  - name: storage-pod
    image: ubuntu:18.04
    command: ["/bin/sh", "-c", "tail -f /dev/null"]
    volumeMounts:
      - name: vol
        mountPath: /data 
        mountPropagation: "HostToContainer"
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: storage-pvc

