apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-admin-dev
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: jane
  namespace: dev

