apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-iptables-tailer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-iptables-tailer
subjects:
- kind: ServiceAccount
  name: kube-iptables-tailer
  namespace: kube-system

