apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-iptables-tailer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs:     ["list","get","watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs:     ["patch","create"]

