apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: all-cluster-pods-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: all-cluster-pods-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: all-cluster-pods-reader
subjects:
- kind: ServiceAccount
  name: all
  namespace: prometheus

